server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: guangzhou #设置事务分组

  application:
    name: order-service
# 加载mybati的全局配置文件
# 加载mybati的全局配置文件
mybatis:
  mapper-locations: com/show/mapper/*.xml
seata:
  registry:
    #配置seata 注册中心 。
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  #seata的配置中心 ，可以读取 seata client 的一些配置
